name: Budowanie i publikacja (Debug + Release)

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
    - name: Klonowanie repozytorium
      uses: actions/checkout@v3

    - name: Konfiguracja MSBuild
      uses: microsoft/setup-msbuild@v1.1

    # DEBUG BUILD
    - name: Budowanie (Debug)
      run: msbuild Sandbox.sln /p:Configuration=Debug

    - name: Upload Debug artifacts
      uses: actions/upload-artifact@v4
      with:
        name: debug-build
        path: ./x64/Debug/

    # TESTY I LOGI
    - name: Uruchomienie testów
      run: .\x64\Debug\TrayIconAppTest.exe --gtest_output=xml:test-results.xml
      continue-on-error: true

    - name: Podgląd zawartości klucza rejestru (HKCU)
      shell: pwsh
      run: |
        $keyPath = "HKCU:\Software\TrayIconApp\TestConfig"
        Write-Host "📍 Sprawdzanie klucza: $keyPath"

        if (Test-Path $keyPath) {
          Get-ItemProperty -Path $keyPath | Format-List | Out-String | Write-Host
        } else {
          Write-Host "❗ Klucz nie istnieje: $keyPath"
        }

    - name: Upload test results (Debug)
      uses: actions/upload-artifact@v4
      with:
        name: test-results-debug
        path: test-results.xml

    # RELEASE BUILD
    - name: Budowanie (Release)
      run: msbuild Sandbox.sln /p:Configuration=Release

    - name: Upload Release artifacts
      uses: actions/upload-artifact@v4
      with:
        name: release-build
        path: ./x64/Release/

    - name: Archiwizacja Release jako ZIP
      run: Compress-Archive -Path x64/Release/* -DestinationPath TrayIconApp_Release.zip

    - name: Upload ZIP z wersją Release
      uses: actions/upload-artifact@v4
      with:
        name: release-zip
        path: TrayIconApp_Release.zip

    # DEBUG ZIP do release
    - name: Archiwizacja Debug jako ZIP
      run: Compress-Archive -Path x64/Debug/* -DestinationPath TrayIconApp_Debug.zip

    # PUBLIC RELEASE
    - name: Tworzenie Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v1.0.${{ github.run_number }}
        name: Wydanie v1.0.${{ github.run_number }}
        body: |
          Automatyczne wydanie wygenerowane przez GitHub Actions.
          Zawiera wersję Debug i Release aplikacji TrayIconApp.
        files: |
          TrayIconApp_Release.zip
          TrayIconApp_Debug.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # CLEANUP
    - name: Usuwanie testowego klucza rejestru (opcjonalne)
      shell: pwsh
      run: Remove-Item -Path "HKCU:\Software\TrayIconApp\TestConfig" -Recurse -Force -ErrorAction SilentlyContinue
