name: Budowanie i publikacja (Debug)

on:
  push:
    branches: [ master ]

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
    - name: Klonowanie repozytorium
      uses: actions/checkout@v3

    - name: Konfiguracja MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Budowanie (Debug)
      run: msbuild Sandbox.sln /p:Configuration=Debug

    - name: Uruchomienie test贸w
      run: D:\a\Sandbox\Sandbox\x64\Debug\TrayIconAppTests.exe --gtest_output=xml:test-results.xml

    - name: Publikacja wynik贸w test贸w jako artefakt CI
      uses: actions/upload-artifact@v4
      with:
        name: test-results-debug
        path: test-results.xml

    - name: Tworzenie release z .exe
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v1.0.${{ github.run_number }}
        name: Wydanie v1.0.${{ github.run_number }}
        body: |
          Automatyczne wydanie wygenerowane przez GitHub Actions.
          Zawiera plik TrayIconApp.exe oraz wynik test贸w.
        files: ./x64/Debug/TrayIconApp.exe
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
