#run: D:\a\Sandbox\Sandbox\x64\Release\TrayIconApp.exe  # Zmień na ścieżkę do Twojego pliku testowego

name: Budowanie i testowanie projektu C++ (Windows)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Klonowanie repozytorium
      uses: actions/checkout@v3

    - name: Ustawienie środowiska MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Budowanie solucji
      run: msbuild Sandbox.sln /p:Configuration=Release

    - name: Uruchomienie testów jednostkowych
      run: D:\a\Sandbox\Sandbox\x64\Release\TrayIconAppTest.exe --gtest_output=xml:test-results.xml

    - name: Publikacja wyników testów
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test-results.xml

    - name: Publikacja pliku wykonywalnego
      uses: actions/upload-artifact@v4
      with:
        name: TrayIconApp.exe
        path: .\x64\Release\TrayIconApp.exe
